OBJS                                   += bfin/dsputil_bfin.o           \
                                          bfin/fdct_bfin.o              \
                                          bfin/idct_bfin.o              \
                                          bfin/mpegvideo_bfin.o         \
                                          bfin/pixels_bfin.o            \
                                          bfin/vp3_bfin.o               \
                                          bfin/vp3_idct_bfin.o          \
                                          bfin/apedec.o \
                                          bfin/avg_bfin.o \
                                          bfin/vp6_bfin.o \
                                          bfin/vp3dsp_bfin.o \
                                          bfin/vp3_filter_bfin.o \
                                          bfin/mc_dma_bfin.o \
                                          bfin/mc_dma.o \
                                          #bfin/mdma.o \

